apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Ensure the role name matches your setup
  # Can include other permissions if required
  name: aws-load-balancer-controller
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingressclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["elbv2.k8s.aws"]
    resources: ["targetgroupbindings"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
