apiVersion: v1
kind: Service
metadata:
  name: react-frontend
  namespace: nutrition
  labels:
    app.kubernetes.io/name: react-frontend
spec:
  selector:
    app.kubernetes.io/name: react-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # changed to 80 from 3000 due to nginx server 
  type: ClusterIP