apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Name of the role
  name: aws-load-balancer-controller-role
rules:
  # List of policies granting permissions to the controller
  - apiGroups: [""]
    resources:
      - namespaces
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
