apiVersion: v1
kind: Service
metadata:
  name: react-frontend
  namespace: nutrition
  labels:
    app.kubernetes.io/name: react-frontend
spec:
  selector:
    app.kubernetes.io/name: react-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP