apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-load-balancer-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aws-load-balancer-controller
    spec:
      serviceAccountName: aws-load-balancer-controller  # Links to IAM role
      containers:
        - name: controller
          image: amazon/aws-alb-ingress-controller:v2.4.5
          imagePullPolicy: Always
          args:
          - --cluster-name=nutrition
          - --aws-region=ap-south-1
