name: Deploy to EKS Manually

on:
  workflow_dispatch:  # Allows manual execution from GitHub UI

jobs:
  deploy:
    name: Apply Kubernetes Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: "ap-south-1"

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Update kubeconfig for EKS Cluster
      run: |
        aws eks update-kubeconfig \
          --name "nutrition" \
          --region "ap-south-1"

    - name: Create Kubernetes Secret for Backend Environment Variables
      run: |
            if ! kubectl get secret aws-credentials --namespace nutrition; then
              kubectl create secret generic aws-credentials \
                --namespace nutrition \
                --from-literal=MONGO_URI=${{ secrets.MONGO_URI }} \
                --from-literal=BUCKET_NAME=${{ secrets.BUCKET_NAME }} \
                --from-literal=BUCKET_URL=${{ secrets.BUCKET_URL }} \
                --from-literal=AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} \
                --from-literal=AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
            else
              echo "Secret aws-credentials already exists."
            fi
    

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f aws-kubernetes/
