name: Deploy to EKS Manually

on:
  workflow_dispatch:  # Allows manual execution from GitHub UI

jobs:
  deploy:
    name: Apply Kubernetes Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ vars.DEFAULT_REGION }}

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Update kubeconfig for EKS Cluster
      run: |
        aws eks update-kubeconfig \
          --name "nutrition" \
          --region ${{ vars.DEFAULT_REGION }}

    - name: Update aws-auth ConfigMap
      run: |
            kubectl patch configmap aws-auth -n kube-system --patch '{
              "mapUsers": [
                {
                  "userarn": "${{ secrets.ROOT_ARN }}", # ARN from GitHub Secrets
                  "username": "admin",
                  "groups": ["system:masters"]
                }
              ]
            }'

    - name: Create Kubernetes Secret from Environment Variables
      env:
            MONGO_URI: ${{ secrets.MONGO_URI }}
            BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
            BUCKET_URL: ${{ secrets.BUCKET_URL }}
            AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      run: |
              # Check if the secret already exists
              if ! kubectl get secret aws-credentials --namespace nutrition; then
                # Create the secret with individual key-value pairs
                kubectl create secret generic aws-credentials \
                  --namespace nutrition \
                  --from-literal=MONGO_URI="$MONGO_URI" \
                  --from-literal=BUCKET_NAME="$BUCKET_NAME" \
                  --from-literal=BUCKET_URL="$BUCKET_URL" \
                  --from-literal=AWS_ACCESS_KEY="$AWS_ACCESS_KEY" \
                  --from-literal=AWS_SECRET_KEY="$AWS_SECRET_KEY" \
                  --dry-run=client -o yaml | kubectl apply -f -
              else
                echo "Secret aws-credentials already exists."
              fi
            
    - name: Verify Secret
      run: kubectl describe secret aws-credentials -n nutrition
    

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f aws-kubernetes/
