name: Deploy to EKS Manually

on:
  workflow_dispatch:  # Allows manual execution from GitHub UI

jobs:
  deploy:
    name: Apply Kubernetes Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: "ap-south-1"

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Update kubeconfig for EKS Cluster
      run: |
        aws eks update-kubeconfig \
          --name "nutrition" \
          --region "ap-south-1"

    - name: Create Kubernetes Secret from Temporary JSON
      env:
            MONGO_URI: ${{ secrets.MONGO_URI }}
            BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
            BUCKET_URL: ${{ secrets.BUCKET_URL }}
            AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      run: |
          # Create a temporary JSON file
          echo '{
              "MONGO_URI": "'$MONGO_URI'",
              "BUCKET_NAME": "'$BUCKET_NAME'",
              "BUCKET_URL": "'$BUCKET_URL'",
              "AWS_ACCESS_KEY": "'$AWS_ACCESS_KEY'",
              "AWS_SECRET_KEY": "'$AWS_SECRET_KEY'"
          }' > temp-secret.json


    - name: Create Kubernetes Secret for Backend Environment Variables
      run: |
            if ! kubectl get secret aws-credentials --namespace nutrition; then
              kubectl create secret generic aws-credentials \
            --namespace nutrition \
            --from-file=temp-secret.json --dry-run=client -o yaml | kubectl apply -f -

            # remove the temporary secret
            rm temp-secret.json
            else
              echo "Secret aws-credentials already exists."
            fi
            
    - name: Verify Secret
      run: kubectl describe secret aws-credentials -n nutrition
    

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f aws-kubernetes/
