name: Deploy the Kubernetes Files Directly

on:
  workflow_dispatch:  # Allows manual execution from GitHub UI

jobs:
  deploy:
    name: Apply Kubernetes Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ vars.DEFAULT_REGION }}

    - name: Install eksctl
      run: |
          # Set architecture and platform
          ARCH=amd64
          PLATFORM=$(uname -s)_$ARCH
      
          # Download eksctl tar.gz file for the platform
          curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
      
          # (Optional) Verify checksum
          curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check
      
          # Extract the tar.gz and move the binary
          tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
      
          # Move eksctl binary to /usr/local/bin
          sudo mv /tmp/eksctl /usr/local/bin
          # Verify eksctl installation
          eksctl version
    

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    
    
    - name: Verify Helm Installation
      run: helm version

    - name: Update kubeconfig for EKS Cluster
      run: |
        aws eks update-kubeconfig \
          --name "nutrition" \
          --region ${{ vars.DEFAULT_REGION }}


    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f aws-kubernetes/
